In [1]:
#First, I imported pandas as pd and the data set provided by the NYT. I coded the data frame to be reaad and stored as variable coviddata. I called the variable to ensure it loaded properly and famliarize myself with the column names. I also imported plotnine and attributes to use later for the graph

In [2]:
import pandas as pd
import plotnine as p9
from plotnine import geom_bar, ggplot, aes, geom_line, labs, theme, geom_point
coviddata = pd.read_csv("us-states.csv")

In [3]:
coviddata

             date          state  fips    cases  deaths
0      2020-01-21     Washington    53        1       0
1      2020-01-22     Washington    53        1       0
2      2020-01-23     Washington    53        1       0
3      2020-01-24       Illinois    17        1       0
4      2020-01-24     Washington    53        1       0
...           ...            ...   ...      ...     ...
61937  2023-03-23       Virginia    51  2298300   23782
61938  2023-03-23     Washington    53  1940704   15905
61939  2023-03-23  West Virginia    54   645710    8132
61940  2023-03-23      Wisconsin    55  2014524   16485
61941  2023-03-23        Wyoming    56   185800    2014

[61942 rows x 5 columns]

In [4]:
#First, I created a function that would add a new column of new case counts to the original coviddata frame. This grouped the data by state, then for cases took the difference and added it to a new column called new_case_count.I stored this new data frame as new_case_count_df and recalled it to ensure the column had added correctly

In [5]:
#Originally, I had created a new case count by extrapolating state specific data into it's own data frame, then adding a column by creating a difference. While creating a seperate state dataframe worked, the other approached allowed for more flexibility and usability throughout the rest of the exercise. Then we could do things like compare peaks between two states without first creating individual data frames.

In [6]:
coviddata['date']=pd.to_datetime(coviddata['date'])

In [7]:
def new_case_count(df):
    df["new_case_count"] = df.groupby(["state"])["cases"].diff().fillna(0)
    return df

In [8]:
new_case_count(coviddata)

            date          state  fips    cases  deaths  new_case_count
0     2020-01-21     Washington    53        1       0             0.0
1     2020-01-22     Washington    53        1       0             0.0
2     2020-01-23     Washington    53        1       0             0.0
3     2020-01-24       Illinois    17        1       0             0.0
4     2020-01-24     Washington    53        1       0             0.0
...          ...            ...   ...      ...     ...             ...
61937 2023-03-23       Virginia    51  2298300   23782           454.0
61938 2023-03-23     Washington    53  1940704   15905             0.0
61939 2023-03-23  West Virginia    54   645710    8132             0.0
61940 2023-03-23      Wisconsin    55  2014524   16485          1039.0
61941 2023-03-23        Wyoming    56   185800    2014             0.0

[61942 rows x 6 columns]

In [9]:
#Originally, I had created a new case count by extrapolating state specific data into it's own data frame, then adding a column by creating a difference. While creating a seperate state dataframe worked, the other approached allowed for more flexibility and usability throughout the rest of the exercise. Then we could do things like compare peaks between two states without first creating individual data frames.

In [10]:
states = ["Washington", "Illinois", "Virginia"]

In [11]:
plot_state = pd.DataFrame()

In [14]:
for state in states:
    state_df = new_case_count(coviddata[coviddata['state']==state])
    plot_state = pd.concat([plot_state, state_df], ignore_index = True)

C:\Users\carol\AppData\Local\Temp\ipykernel_21688\2382091534.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\carol\AppData\Local\Temp\ipykernel_21688\2382091534.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\Users\carol\AppData\Local\Temp\ipykernel_21688\2382091534.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [15]:
plot_state

           date       state  fips    cases  deaths  new_case_count
0    2020-01-21  Washington    53        1       0             0.0
1    2020-01-22  Washington    53        1       0             0.0
2    2020-01-23  Washington    53        1       0             0.0
3    2020-01-24  Washington    53        1       0             0.0
4    2020-01-25  Washington    53        1       0             0.0
...         ...         ...   ...      ...     ...             ...
3420 2023-03-19    Virginia    51  2296086   23775             0.0
3421 2023-03-20    Virginia    51  2296996   23775           910.0
3422 2023-03-21    Virginia    51  2297406   23782           410.0
3423 2023-03-22    Virginia    51  2297846   23782           440.0
3424 2023-03-23    Virginia    51  2298300   23782           454.0

[3425 rows x 6 columns]

In [17]:
g = ggplot(plot_state, p9.aes(x='date', y='new_case_count', color='state'))+ p9.geom_line()+ p9.labs(title = 'New COVID Cases by State')+ p9.theme(axis_text_x=p9.element_text(angle=45))

In [20]:
g.save('state_graphs.png')

C:\Users\carol\anaconda3\Lib\site-packages\plotnine\ggplot.py:630: PlotnineWarning: Saving 6.4 x 4.8 in image.
C:\Users\carol\anaconda3\Lib\site-packages\plotnine\ggplot.py:631: PlotnineWarning: Filename: state_graphs.png

In [ ]:
#So, my function to plot states based on case counts is based on this

In [ ]:
#First, created

In [ ]:
def date_of_peak(df, state):
    data2 = new_case_count(df)
    data3 = data2[data2["state"]==state]
    max_case_count = data3["new_case_count"].idxmax()
    max_case_row = data3.loc[max_case_count,"date"]
    return max_case_row

In [ ]:
date_of_peak(coviddata, "Wyoming")

In [ ]:
 def compare(df, state1, state2):
    peak_date1 = date_of_peak(df, state1)
    peak_date2 = date_of_peak(df, state2)
    delta = abs((peak_date1 - peak_date2).days)
    if peak_date1 > peak_date2:
        earlier_date = peak_date2
        earlier_state = state2
        later_date = peak_date1
        later_state = state1
        return(f"{state2} had its peak first and the peak was {delta} days apart")
    elif peak_date1 < peak_date2:
        earlier_date = peak_date1
        earlier_state = state1
        later_date = peak_date2
        later_state = state2
        return(f"{state1} had its peak first and the peak was {delta} days apart")
    elif peak_date1 == peak_date2:
        return(f"{state2} and {state1} had its peak on the same day")

In [ ]:
compare(coviddata, "Florida", "Wyoming")

In [ ]:
florida = coviddata[coviddata['state']=='Florida']

In [ ]:
florida

In [ ]:
florida.describe()

In [ ]:
g = ggplot(florida, p9.aes(x='date', y='new_case_count', color='state'))+ p9.geom_line()+ p9.labs(title = 'New COVID Cases by State')+ p9.theme(axis_text_x=p9.element_text(angle=45))

In [ ]:
g.save('florida.png')