Needed: 
summary statistics are probably worth doing, but do something more than just summary statistics.
At least two of the analyses should generate graphable data.
At least one of the analyses should take a parameter. (e.g. the k in k-nearest neighbors)


Plan:
RUCC - classification of county
predict #of beds, providers, operating rooms, ER(?) based on POS Q4s from 2013-2023 based on rural vs metro (generate graphs)
clustering of distance to ER, urgent care, and medsurge ICU in SDOH 
summary statisticss of SDOH (standardized)

Questions:
is it okay to use the different datasets
how do we account for large counties or population sizes
how are we going to validate (could i tkae in a county and google that distance to hospital etc)

Still Need to Do:
Check for summary statistics/missing values/outliers
    Summary Stats: distribution of classifications in country - can you do summary statistics of this; Per rural vs metro mean, median etc each year?; mean median of maximum distances per classification 
Preprocessing
Validate and run analyses

In [51]:
import requests
import pandas as pd

In [52]:
# import api 

data_25q2 = (requests.get(f"https://data.cms.gov/data-api/v1/dataset/8ba0f9b4-9493-4aa0-9f82-44ea9468d1b5/data", headers={"User-Agent": "MyScript"}).json())

In [ ]:
df_25q2 = pd.DataFrame(data_25q2)
#df_25q2 = df_25q2[["SSA_CNTY_CD","PRVDR_CTGRY_SBTYP_CD", "STATE_CD","CBSA_URBN_RRL_IND", "AFLTD_PRVDR_CNT", "BED_CNT", "TOT_OFSITE_EMER_DEPT_CNT","TOT_OFSITE_LTC_HOSP_CNT", "TOT_OFSITE_URGNT_CARE_CNTR_CNT", "OPRTG_ROOM_CNT"]]
df_25q2.head()
 #

,PRVDR_CTGRY_SBTYP_CD,PRVDR_CTGRY_CD,CHOW_CNT,CHOW_DT,CITY_NAME,ACPTBL_POC_SW,CMPLNC_STUS_CD,SSA_CNTY_CD,CROSS_REF_PROVIDER_NUMBER,CRTFCTN_DT,...,OTHR_SRGRY_SW,PAIN_SRGRY_SW,PLSTC_SRGRY_SW,FT_SRGRY_SW,SB_SW,SB_SIZE_CD,TCHNLGST_2_YR_RDLGC_CNT,TCHNLGST_ASCT_DGR_CNT,TCHNLGST_BS_BA_DGR_CNT,DLYS_STN_CNT
0,01,01,1,,DOTHAN,N,B,340,010163,20171005,...,,,,,N,,,,,
1,01,01,0,,BRIDGEPORT,N,A,350,,20010316,...,,,,,N,,,,,
2,01,01,0,,BOAZ,Y,A,470,,20021003,...,,,,,N,,,,,
3,01,01,1,20100701,FLORENCE,N,B,380,,20190411,...,,,,,N,,,,,
4,01,01,0,,OPP,N,B,190,,20241212,...,,,,,Y,2,,,,

In [54]:
df_25q2[["AFLTD_PRVDR_CNT","BED_CNT","TOT_OFSITE_EMER_DEPT_CNT", "TOT_OFSITE_LTC_HOSP_CNT",  "TOT_OFSITE_URGNT_CARE_CNTR_CNT", "OPRTG_ROOM_CNT" ]].apply(pd.to_numeric, errors="coerce").sum()

AFLTD_PRVDR_CNT                      57.0
BED_CNT                           35324.0
TOT_OFSITE_EMER_DEPT_CNT             13.0
TOT_OFSITE_LTC_HOSP_CNT               0.0
TOT_OFSITE_URGNT_CARE_CNTR_CNT        0.0
OPRTG_ROOM_CNT                      300.0
dtype: float64

In [55]:
#2025 Q1 data and df

data_25q1 = (requests.get(f"https://data.cms.gov/data-api/v1/dataset/315bbdac-3888-43d9-9012-a9a2e29ca179/data", headers={"User-Agent": "MyScript"}).json())

In [56]:
df_25q1 = pd.DataFrame(data_25q1)
df_25q1 = df_25q1[["SSA_CNTY_CD","PRVDR_CTGRY_SBTYP_CD", "STATE_CD","CBSA_URBN_RRL_IND", "AFLTD_PRVDR_CNT", "BED_CNT", "TOT_OFSITE_EMER_DEPT_CNT","TOT_OFSITE_LTC_HOSP_CNT", "TOT_OFSITE_URGNT_CARE_CNTR_CNT", "OPRTG_ROOM_CNT"]]
df_25q1.head()

,SSA_CNTY_CD,PRVDR_CTGRY_SBTYP_CD,STATE_CD,CBSA_URBN_RRL_IND,AFLTD_PRVDR_CNT,BED_CNT,TOT_OFSITE_EMER_DEPT_CNT,TOT_OFSITE_LTC_HOSP_CNT,TOT_OFSITE_URGNT_CARE_CNTR_CNT,OPRTG_ROOM_CNT
0,340,01,AL,U,1,420,0,0,0,23
1,350,01,AL,R,0,64,0,0,0,0
2,470,01,AL,R,0,240,0,0,0,0
3,380,01,AL,U,0,338,0,0,0,17
4,190,01,AL,R,1,99,1,0,0,2

In [57]:
df_25q1[["AFLTD_PRVDR_CNT","BED_CNT","TOT_OFSITE_EMER_DEPT_CNT", "TOT_OFSITE_LTC_HOSP_CNT",  "TOT_OFSITE_URGNT_CARE_CNTR_CNT", "OPRTG_ROOM_CNT" ]].apply(pd.to_numeric, errors="coerce").sum()

AFLTD_PRVDR_CNT                      53.0
BED_CNT                           35288.0
TOT_OFSITE_EMER_DEPT_CNT             13.0
TOT_OFSITE_LTC_HOSP_CNT               0.0
TOT_OFSITE_URGNT_CARE_CNTR_CNT        0.0
OPRTG_ROOM_CNT                      298.0
dtype: float64

In [58]:
#2024 Q4 data and df

data_24q4 = (requests.get(f"https://data.cms.gov/data-api/v1/dataset/8143cbc7-484f-438b-9dfa-2e81d5d6a1ed/data", headers={"User-Agent": "MyScript"}).json())

In [59]:
df_24q4 = pd.DataFrame(data_24q4)
df_24q4 = df_24q4[["SSA_CNTY_CD","PRVDR_CTGRY_SBTYP_CD", "STATE_CD","CBSA_URBN_RRL_IND", "AFLTD_PRVDR_CNT", "BED_CNT", "TOT_OFSITE_EMER_DEPT_CNT","TOT_OFSITE_LTC_HOSP_CNT", "TOT_OFSITE_URGNT_CARE_CNTR_CNT", "OPRTG_ROOM_CNT"]]
df_24q4.head()

,SSA_CNTY_CD,PRVDR_CTGRY_SBTYP_CD,STATE_CD,CBSA_URBN_RRL_IND,AFLTD_PRVDR_CNT,BED_CNT,TOT_OFSITE_EMER_DEPT_CNT,TOT_OFSITE_LTC_HOSP_CNT,TOT_OFSITE_URGNT_CARE_CNTR_CNT,OPRTG_ROOM_CNT
0,340,01,AL,U,1,420,0,0,0,23
1,350,01,AL,R,0,64,0,0,0,0
2,470,01,AL,R,0,240,0,0,0,0
3,380,01,AL,U,0,338,0,0,0,17
4,190,01,AL,R,1,99,1,0,0,2

In [60]:
df_24q4[["AFLTD_PRVDR_CNT","BED_CNT","TOT_OFSITE_EMER_DEPT_CNT", "TOT_OFSITE_LTC_HOSP_CNT",  "TOT_OFSITE_URGNT_CARE_CNTR_CNT", "OPRTG_ROOM_CNT" ]].apply(pd.to_numeric, errors="coerce").sum()

AFLTD_PRVDR_CNT                      50.0
BED_CNT                           35353.0
TOT_OFSITE_EMER_DEPT_CNT             13.0
TOT_OFSITE_LTC_HOSP_CNT               0.0
TOT_OFSITE_URGNT_CARE_CNTR_CNT        0.0
OPRTG_ROOM_CNT                      296.0
dtype: float64

In [61]:
#2024 Q3 data and df

data_24q3 = (requests.get(f"https://data.cms.gov/data-api/v1/dataset/6b6a53a6-0020-4895-bdfe-c5a9f1733734/data", headers={"User-Agent": "MyScript"}).json())

In [62]:
df_24q3 = pd.DataFrame(data_24q3)
df_24q3 = df_24q3[["SSA_CNTY_CD","PRVDR_CTGRY_SBTYP_CD", "STATE_CD","CBSA_URBN_RRL_IND", "AFLTD_PRVDR_CNT", "BED_CNT", "TOT_OFSITE_EMER_DEPT_CNT","TOT_OFSITE_LTC_HOSP_CNT", "TOT_OFSITE_URGNT_CARE_CNTR_CNT", "OPRTG_ROOM_CNT"]]
df_24q3.head()

,SSA_CNTY_CD,PRVDR_CTGRY_SBTYP_CD,STATE_CD,CBSA_URBN_RRL_IND,AFLTD_PRVDR_CNT,BED_CNT,TOT_OFSITE_EMER_DEPT_CNT,TOT_OFSITE_LTC_HOSP_CNT,TOT_OFSITE_URGNT_CARE_CNTR_CNT,OPRTG_ROOM_CNT
0,340,01,AL,U,1,420,0,0,0,23
1,350,01,AL,R,0,64,0,0,0,0
2,470,01,AL,R,0,240,0,0,0,0
3,380,01,AL,U,0,338,0,0,0,17
4,190,01,AL,R,1,99,1,0,0,2

In [63]:
df_24q3[["AFLTD_PRVDR_CNT","BED_CNT","TOT_OFSITE_EMER_DEPT_CNT", "TOT_OFSITE_LTC_HOSP_CNT",  "TOT_OFSITE_URGNT_CARE_CNTR_CNT", "OPRTG_ROOM_CNT" ]].apply(pd.to_numeric, errors="coerce").sum()

AFLTD_PRVDR_CNT                      50.0
BED_CNT                           35352.0
TOT_OFSITE_EMER_DEPT_CNT             13.0
TOT_OFSITE_LTC_HOSP_CNT               0.0
TOT_OFSITE_URGNT_CARE_CNTR_CNT        0.0
OPRTG_ROOM_CNT                      292.0
dtype: float64

In [64]:
#2024 Q2 data and df

data_24q2 = (requests.get(f"https://data.cms.gov/data-api/v1/dataset/b3a134d0-6399-4809-9458-f02f3560e85a/data", headers={"User-Agent": "MyScript"}).json())

In [65]:
df_24q2 = pd.DataFrame(data_24q2)
df_24q2 = df_24q2[["SSA_CNTY_CD","PRVDR_CTGRY_SBTYP_CD", "STATE_CD","CBSA_URBN_RRL_IND", "AFLTD_PRVDR_CNT", "BED_CNT", "TOT_OFSITE_EMER_DEPT_CNT","TOT_OFSITE_LTC_HOSP_CNT", "TOT_OFSITE_URGNT_CARE_CNTR_CNT", "OPRTG_ROOM_CNT"]]
df_24q2.head()

,SSA_CNTY_CD,PRVDR_CTGRY_SBTYP_CD,STATE_CD,CBSA_URBN_RRL_IND,AFLTD_PRVDR_CNT,BED_CNT,TOT_OFSITE_EMER_DEPT_CNT,TOT_OFSITE_LTC_HOSP_CNT,TOT_OFSITE_URGNT_CARE_CNTR_CNT,OPRTG_ROOM_CNT
0,340,01,AL,U,1,420,0,0,0,23
1,350,01,AL,R,0,64,0,0,0,0
2,470,01,AL,R,0,240,0,0,0,0
3,380,01,AL,U,0,338,0,0,0,17
4,190,01,AL,R,1,99,1,0,0,2

In [66]:
df_24q2[["AFLTD_PRVDR_CNT","BED_CNT","TOT_OFSITE_EMER_DEPT_CNT", "TOT_OFSITE_LTC_HOSP_CNT",  "TOT_OFSITE_URGNT_CARE_CNTR_CNT", "OPRTG_ROOM_CNT" ]].apply(pd.to_numeric, errors="coerce").sum()

AFLTD_PRVDR_CNT                      49.0
BED_CNT                           35365.0
TOT_OFSITE_EMER_DEPT_CNT             13.0
TOT_OFSITE_LTC_HOSP_CNT               0.0
TOT_OFSITE_URGNT_CARE_CNTR_CNT        0.0
OPRTG_ROOM_CNT                      292.0
dtype: float64

In [67]:
#2024 Q1 data and df

data_24q1= (requests.get(f"https://data.cms.gov/data-api/v1/dataset/1a4586e7-6ea8-427b-9eca-2aaf25f2fd12/data", headers={"User-Agent": "MyScript"}).json())

In [68]:
df_24q1 = pd.DataFrame(data_24q1)
df_24q1 = df_24q1[["SSA_CNTY_CD","PRVDR_CTGRY_SBTYP_CD", "STATE_CD","CBSA_URBN_RRL_IND", "AFLTD_PRVDR_CNT", "BED_CNT", "TOT_OFSITE_EMER_DEPT_CNT","TOT_OFSITE_LTC_HOSP_CNT", "TOT_OFSITE_URGNT_CARE_CNTR_CNT", "OPRTG_ROOM_CNT"]]
df_24q1.head()

,SSA_CNTY_CD,PRVDR_CTGRY_SBTYP_CD,STATE_CD,CBSA_URBN_RRL_IND,AFLTD_PRVDR_CNT,BED_CNT,TOT_OFSITE_EMER_DEPT_CNT,TOT_OFSITE_LTC_HOSP_CNT,TOT_OFSITE_URGNT_CARE_CNTR_CNT,OPRTG_ROOM_CNT
0,340,01,AL,U,1,420,0,0,0,23
1,350,01,AL,R,0,64,0,0,0,0
2,470,01,AL,R,0,240,0,0,0,0
3,380,01,AL,U,0,338,0,0,0,17
4,190,01,AL,R,1,99,1,0,0,2

In [69]:
df_24q1[["AFLTD_PRVDR_CNT","BED_CNT","TOT_OFSITE_EMER_DEPT_CNT", "TOT_OFSITE_LTC_HOSP_CNT",  "TOT_OFSITE_URGNT_CARE_CNTR_CNT", "OPRTG_ROOM_CNT" ]].apply(pd.to_numeric, errors="coerce").sum()

AFLTD_PRVDR_CNT                      49.0
BED_CNT                           35309.0
TOT_OFSITE_EMER_DEPT_CNT             13.0
TOT_OFSITE_LTC_HOSP_CNT               0.0
TOT_OFSITE_URGNT_CARE_CNTR_CNT        0.0
OPRTG_ROOM_CNT                      292.0
dtype: float64

In [70]:
len(df_25q2)

1000

In [72]:
print(df_25q2.columns.tolist())

['PRVDR_CTGRY_SBTYP_CD', 'PRVDR_CTGRY_CD', 'CHOW_CNT', 'CHOW_DT', 'CITY_NAME', 'ACPTBL_POC_SW', 'CMPLNC_STUS_CD', 'SSA_CNTY_CD', 'CROSS_REF_PROVIDER_NUMBER', 'CRTFCTN_DT', 'ELGBLTY_SW', 'FAC_NAME', 'INTRMDRY_CARR_CD', 'MDCD_VNDR_NUM', 'ORGNL_PRTCPTN_DT', 'CHOW_PRIOR_DT', 'INTRMDRY_CARR_PRIOR_CD', 'PRVDR_NUM', 'RGN_CD', 'SKLTN_REC_SW', 'STATE_CD', 'SSA_STATE_CD', 'STATE_RGN_CD', 'ST_ADR', 'PHNE_NUM', 'PGM_TRMNTN_CD', 'TRMNTN_EXPRTN_DT', 'CRTFCTN_ACTN_TYPE_CD', 'GNRL_CNTL_TYPE_CD', 'ZIP_CD', 'FIPS_STATE_CD', 'FIPS_CNTY_CD', 'CBSA_URBN_RRL_IND', 'CBSA_CD', 'ACRDTN_EFCTV_DT', 'ACRDTN_EXPRTN_DT', 'ACRDTN_TYPE_CD', 'TOT_AFLTD_AMBLNC_SRVC_CNT', 'TOT_AFLTD_ASC_CNT', 'TOT_COLCTD_HOSP_CNT', 'TOT_AFLTD_ESRD_CNT', 'TOT_AFLTD_FQHC_CNT', 'TOT_AFLTD_HHA_CNT', 'TOT_AFLTD_HOSPC_CNT', 'TOT_AFLTD_OPO_CNT', 'TOT_AFLTD_PRTF_CNT', 'TOT_AFLTD_RHC_CNT', 'TOT_AFLTD_SNF_CNT', 'AFLTD_PRVDR_CNT', 'RSDNT_PGM_ALPTHC_SW', 'RSDNT_PGM_DNTL_SW', 'RSDNT_PGM_OSTPTHC_SW', 'RSDNT_PGM_OTHR_SW', 'RSDNT_PGM_PDTRC_SW', 'LAB_SRVC_CD', 'PHRMCY_SRVC_CD', 'RDLGY_SRVC_CD', 'ASC_BGN_SRVC_DT', 'FREESTNDNG_ASC_SW', 'OVRRD_BED_CNT_SW', 'CRTFD_BED_CNT', 'ICFIID_BED_CNT', 'MDCD_NF_BED_CNT', 'MDCR_SNF_BED_CNT', 'MDCR_MDCD_SNF_BED_CNT', 'AIDS_BED_CNT', 'ALZHMR_BED_CNT', 'DLYS_BED_CNT', 'DSBL_CHLDRN_BED_CNT', 'HEAD_TRMA_BED_CNT', 'HOSPC_BED_CNT', 'HNTGTN_DEASE_BED_CNT', 'REHAB_BED_CNT', 'VNTLTR_BED_CNT', 'BED_CNT', 'BRNCH_CNT', 'BRNCH_OPRTN_SW', 'CAH_PSYCH_DPU_SW', 'CAH_REHAB_DPU_SW', 'CAH_SB_SW', 'CRDC_CTHRTZTN_PRCDR_ROOMS_CNT', 'GNRL_FAC_TYPE_CD', 'CHOW_SW', 'CLIA_ID_NUMBER_1', 'CLIA_ID_NUMBER_2', 'CLIA_ID_NUMBER_3', 'CLIA_ID_NUMBER_4', 'CLIA_ID_NUMBER_5', 'COLCTN_STUS_SW', 'RN_24_HR_WVR_SW', 'RN_7_DAY_WVR_SW', 'BED_PER_ROOM_WVR_SW', 'LSC_WVR_SW', 'ROOM_SIZE_WVR_SW', 'ENDSCPY_PRCDR_ROOMS_CNT', 'ESRD_NTWRK_NUM', 'EXPRMT_RSRCH_CNDCTD_SW', 'FAX_PHNE_NUM', 'FY_END_MO_DAY_CD', 'FQHC_APPROVED_RHC_PROVIDER_NUM', 'FED_FUNDD_FQHC_SW', 'HHA_QLFYD_OPT_SPCH_SW', 'HH_AIDE_TRNG_PGM_CD', 'HOME_TRNG_SPRT_ONLY_SRVC_SW', 'MDCR_HOSPC_SW', 'HOSP_BSD_SW', 'INCNTR_NCTRNL_SRVC_SW', 'LTC_CROSS_REF_PROVIDER_NUMBER', 'MDCL_SCHL_AFLTN_CD', 'MEDICARE_HOSPICE_PROVIDER_NUM', 'MDCD_MDCR_PRTCPTG_PRVDR_SW', 'MEDICARE_MEDICAID_PRVDR_NUMBER', 'MLT_FAC_ORG_NAME', 'MLT_OWND_FAC_ORG_SW', 'NCRY_PRVDR_DSGNTD_DT', 'NCRY_PRVDR_DSGNTD_AS_SW', 'NCRY_PRVDR_LOST_DT', 'MEET_1861_SW', 'NPP_TYPE_CD', 'TOT_OFSITE_CNCR_HOSP_CNT', 'TOT_OFSITE_CHLDRN_HOSP_CNT', 'TOT_OFSITE_EMER_DEPT_CNT', 'TOT_OFSITE_INPTNT_LCTN_CNT', 'TOT_OFSITE_LTC_HOSP_CNT', 'TOT_OFSITE_OPTHLMC_SRGRY_CNT', 'TOT_OFSITE_OTHR_LCTN_CNT', 'TOT_OFSITE_PSYCH_HOSP_CNT', 'TOT_OFSITE_PSYCH_UNIT_CNT', 'TOT_OFSITE_REHAB_HOSP_CNT', 'TOT_OFSITE_REHAB_UNIT_CNT', 'TOT_OFSITE_URGNT_CARE_CNTR_CNT', 'OFSITE_LCTN_CNT', 'OPRTG_ROOM_CNT', 'ORGNZ_FMLY_MBR_GRP_SW', 'ORGNZ_RSDNT_GRP_SW', 'PARENT_PROVIDER_NUMBER', 'FQHC_APRVD_RHC_SW', 'MDCR_PRTCPTN_OP_PT_SPCH_SW', 'PGM_PRTCPTN_CD', 'PRVDR_BSD_FAC_SW', 'PRVNC_CD', 'PSYCH_UNIT_BED_CNT', 'PSYCH_UNIT_EFCTV_DT', 'PSYCH_UNIT_SW', 'PSYCH_UNIT_TRMNTN_CD', 'PSYCH_UNIT_TRMNTN_DT', 'REHAB_UNIT_BED_CNT', 'REHAB_UNIT_EFCTV_DT', 'REHAB_UNIT_SW', 'REHAB_UNIT_TRMNTN_CD', 'REHAB_UNIT_TRMNTN_DT', 'RELATED_PROVIDER_NUMBER', 'ACUTE_RNL_DLYS_SRVC_CD', 'PSYCH_SRVC_CD', 'HH_AIDE_SRVC_CD', 'ALCHL_DRUG_SRVC_CD', 'ANSTHSA_SRVC_CD', 'APLNC_EQUIP_SRVC_CD', 'AUDLGY_SRVC_CD', 'BLOOD_SRVC_OFSITE_RSDNT_SW', 'BLOOD_SRVC_ONST_NRSDNT_SW', 'BLOOD_SRVC_ONST_RSDNT_SW', 'BURN_CARE_UNIT_SRVC_CD', 'CRDC_CTHRTZTN_LAB_SRVC_CD', 'OPEN_HRT_SRGRY_SRVC_CD', 'CARF_IP_REHAB_SRVC_CD', 'CHMTHRPY_SRVC_CD', 'CHRPRCTIC_SRVC_CD', 'CL_SRVC_OFSITE_RSDNT_SW', 'CL_SRVC_ONST_NRSDNT_SW', 'CL_SRVC_ONST_RSDNT_SW', 'CL_SRVC_CD', 'CRNRY_CARE_UNIT_SRVC_CD', 'CNSLNG_SRVC_CD', 'CT_SCAN_SRVC_CD', 'DNTL_SRVC_CD', 'DNTL_SRVC_OFSITE_RSDNT_SW', 'DNTL_SRVC_ONST_NRSDNT_SW', 'DNTL_SRVC_ONST_RSDNT_SW', 'SHCK_TRMA_SRVC_CD', 'DGNSTC_RDLGY_SRVC_CD', 'DTRY_SRVC_CD', 'DTRY_OFSITE_RSDNT_SW', 'DTRY_ONST_NRSDNT_SW', 'DTRY_ONST_RSDNT_SW', 'DCTD_ER_SRVC_CD', 'EMER_PSYCH_SRVC_CD', 'XTRCRPRL_SHCK_LTHTRPTR_SRVC_CD', 'FRNSC_PSYCH_SRVC_CD', 'GRTRC_PSYCH_SRVC_CD', 'GRNTLGCL_SPCLTY_SRVC_CD', 'SP_HOME_TRNG_SPRT_HD_SW', 'HMDLYS_SRVC_SW', 'HMMKR_SRVC_CD', 'HSEKPNG_SRVC_OFSITE_RSDNT_SW', 'HSEKPNG_SRVC_ONST_NRSDNT_SW', 'HSEKPNG_SRVC_ONST_RSDNT_SW', 'IP_SRGCL_SRVC_CD', 'INTRN_RSDNT_SRVC_CD', 'MDCL_SCL_SRVC_CD', 'MDCL_SUPLY_SRVC_CD', 'ICU_SRVC_CD', 'MDCR_TRNSPLNT_CNTR_SRVC_CD', 'MENTL_HLTH_OFSITE_RSDNT_SW', 'MENTL_HLTH_ONST_NRSDNT_SW', 'MENTL_HLTH_ONST_RSDNT_SW', 'MGNTC_RSNC_IMG_SRVC_CD', 'NEONTL_ICU_SRVC_CD', 'NEONTL_NRSRY_SRVC_CD', 'NRSRGCL_SRVC_CD', 'ORGN_TRNSPLNT_SRVC_CD', 'NUCLR_MDCN_SRVC_CD', 'NRSNG_SRVC_EMPLEE_SW', 'NRSNG_SRVC_CNTRCTR_SW', 'NRSNG_SRVC_ARNGMT_SW', 'NRSNG_SRVC_CD', 'NRSNG_SRVC_OFSITE_RSDNT_SW', 'NRSNG_SRVC_ONST_NRSDNT_SW', 'NRSNG_SRVC_ONST_RSDNT_SW', 'NTRTNL_GDNC_SRVC_CD', 'OB_SRVC_CD', 'OPTHLMC_SRGY_SRVC_CD', 'OPTMTRC_SRVC_CD', 'OPRTG_ROOM_SRVC_CD', 'ORTHPDC_SRGY_SRVC_CD', 'ORTHTC_PRSTHTC_EMPLEE_SW', 'ORTHTC_PRSTHTC_CNTRCTR_SW', 'ORTHTC_PRSTHTC_ARNGMT_SW', 'OT_EMPLEE_SW', 'OT_CNTRCTR_SW', 'OT_ARNGMT_SW', 'OT_SRVC_CD', 'OT_SRVC_OFSITE_RSDNT_SW', 'OT_SRVC_ONST_NRSDNT_SW', 'OT_SRVC_ONST_RSDNT_SW', 'OTHR_SRVC_CD', 'OP_SRVC_CD', 'OP_PSYCH_SRVC_CD', 'OP_REHAB_SRVC_CD', 'OP_SRGRY_UNIT_SRVC_CD', 'PED_SRVC_CD', 'PED_ICU_SRVC_CD', 'SP_HOME_TRNG_SPRT_PD_SW', 'PRTNL_DLYS_SRVC_SW', 'PET_SCAN_SRVC_CD', 'PHRMCY_SRVC_OFSITE_RSDNT_SW', 'PHRMCY_SRVC_ONST_NRSDNT_SW', 'PHRMCY_SRVC_ONST_RSDNT_SW', 'PHYSN_EMPLEE_SW', 'PHYSN_CNTRCTR_SW', 'PHYSN_ARNGMT_SW', 'PHYSN_SRVC_CD', 'PHYSN_EXT_SRVC_OFSITE_RSDNT_SW', 'PHYSN_EXT_SRVC_ONST_NRSDNT_SW', 'PHYSN_EXT_SRVC_ONST_RSDNT_SW', 'PHYSN_SRVC_OFSITE_RSDNT_SW', 'PHYSN_SRVC_ONST_NRSDNT_SW', 'PHYSN_SRVC_ONST_RSDNT_SW', 'PDTRY_SRVC_OFSITE_RSDNT_SW', 'PDTRY_SRVC_ONST_NRSDNT_SW', 'PDTRY_SRVC_ONST_RSDNT_SW', 'PSTOPRTV_RCVRY_SRVC_CD', 'CHLD_ADLSCNT_PSYCH_SRVC_CD', 'PSYCHLGCL_EMPLEE_SW', 'PSYCHLGCL_CNTRCTR_SW', 'PSYCHLGCL_ARNGMT_SW', 'PT_EMPLEE_SW', 'PT_CNTRCTR_SW', 'PT_ARNGMT_SW', 'PT_SRVC_CD', 'PT_OFSITE_RSDNT_SW', 'PT_ONST_NRSDNT_SW', 'PT_ONST_RSDNT_SW', 'RCNSTRCTN_SRGY_SRVC_CD', 'RSPRTRY_CARE_EMPLEE_SW', 'RSPRTRY_CARE_CNTRCTR_SW', 'RSPRTRY_CARE_ARNGMT_SW', 'RSPRTRY_CARE_SRVC_CD', 'SHRT_TERM_IP_SRVC_CD', 'SCL_EMPLEE_SW', 'SCL_CNTRCTR_SW', 'SCL_ARNGMT_SW', 'SCL_SRVC_CD', 'SCL_WORK_SRVC_OFSITE_RSDNT_SW', 'SCL_WORK_SRVC_ONST_NRSDNT_SW', 'SCL_WORK_SRVC_ONST_RSDNT_SW', 'SPCH_PTHLGY_EMPLEE_SW', 'SPCH_PTHLGY_CNTRCTR_SW', 'SPCH_PTHLGY_ARNGMT_SW', 'SPCH_PTHLGY_SRVC_CD', 'SPCH_PTHLGY_OFSITE_RSDNT_SW', 'SPCH_PTHLGY_ONST_NRSDNT_SW', 'SPCH_PTHLGY_ONST_RSDNT_SW', 'SPCH_THRPY_SRVC_CD', 'SRGCL_ICU_SRVC_CD', 'ACTVTY_OTHR_OFSITE_RSDNT_SW', 'ACTVTY_OTHR_ONST_NRSDNT_SW', 'ACTVTY_OTHR_ONST_RSDNT_SW', 'SCL_SRVC_OTHR_OFSITE_RSDNT_SW', 'SCL_SRVC_OTHR_ONST_NRSDNT_SW', 'SCL_SRVC_OTHR_ONST_RSDNT_SW', 'ACTVTY_OFSITE_RSDNT_SW', 'ACTVTY_ONST_NRSDNT_SW', 'ACTVTY_ONST_RSDNT_SW', 'THRPTC_RDLGY_SRVC_CD', 'THRPTC_RCRTNL_OFSITE_RSDNT_SW', 'THRPTC_RCRTNL_ONST_NRSDNT_SW', 'THRPTC_RCRTNL_ONST_RSDNT_SW', 'URGNT_CARE_SRVC_CD', 'VCTNL_GDNC_SRVC_CD', 'VCTNL_SRVC_OFSITE_RSDNT_SW', 'VCTNL_SRVC_ONST_NRSDNT_SW', 'VCTNL_SRVC_ONST_RSDNT_SW', 'DGNSTC_XRAY_OFSITE_RSDNT_SW', 'DGNSTC_XRAY_ONST_NRSDNT_SW', 'DGNSTC_XRAY_ONST_RSDNT_SW', 'ACUTE_RESP_CARE_CD', 'OVRRD_STFG_SW', 'PROFNL_ADMIN_CNTRCT_CNT', 'PROFNL_ADMIN_FLTM_CNT', 'PROFNL_ADMIN_PRTM_CNT', 'HH_AIDE_EMPLEE_CNT', 'HH_AIDE_VLNTR_CNT', 'PRSNEL_OTHR_CNT', 'NRS_AIDE_CNTRCT_CNT', 'NRS_AIDE_FLTM_CNT', 'NRS_AIDE_PRTM_CNT', 'CNSLR_EMPLEE_CNT', 'CNSLR_VLNTR_CNT', 'CRNA_CNT', 'DNTST_CNTRCT_CNT', 'DNTST_FLTM_CNT', 'DNTST_PRTM_CNT', 'DIETN_CNT', 'DIETN_CNTRCT_CNT', 'DIETN_FLTM_CNT', 'DIETN_PRTM_CNT', 'DRCT_CARE_PRSNEL_CNT', 'FOOD_SRVC_CNTRCT_CNT', 'FOOD_SRVC_FLTM_CNT', 'FOOD_SRVC_PRTM_CNT', 'HH_AIDE_CNT', 'HMMKR_EMPLEE_CNT', 'HMMKR_VLNTR_CNT', 'HSEKPNG_CNTRCT_CNT', 'HSEKPNG_FLTM_CNT', 'HSEKPNG_PRTM_CNT', 'LAB_TCHNCN_CNT', 'LPN_CNT', 'LPN_LVN_CNT', 'LPN_LVN_CNTRCT_CNT', 'LPN_LVN_FLTM_CNT', 'LPN_LVN_PRTM_CNT', 'LPN_LVN_VLNTR_CNT', 'MDCL_DRCTR_CNTRCT_CNT', 'MDCL_DRCTR_FLTM_CNT', 'MDCL_DRCTR_PRTM_CNT', 'MDCL_SCL_WORKR_CNT', 'MDCL_SCL_WORKR_VLNTR_CNT', 'MDCL_TCHNLGST_CNT', 'MDCTN_AIDE_CNTRCT_CNT', 'MDCTN_AIDE_FLTM_CNT', 'MDCTN_AIDE_PRTM_CNT', 'MENTL_HLTH_SRVC_CNTRCT_CNT', 'MENTL_HLTH_SRVC_FLTM_CNT', 'MENTL_HLTH_SRVC_PRTM_CNT', 'NUCLR_MDCN_TCHNCN_CNT', 'NAT_CNTRCT_CNT', 'NAT_FLTM_CNT', 'NAT_PRTM_CNT', 'NRS_PRCTNR_CNT', 'NRS_ADMINV_CNTRCT_CNT', 'NRS_ADMINV_FLTM_CNT', 'NRS_ADMINV_PRTM_CNT', 'OCPTNL_THRPST_CNT', 'OCPTNL_THRPST_CNTRCT_CNT', 'OCPTNL_THRPST_FLTM_CNT', 'OCPTNL_THRPST_PRTM_CNT', 'OT_AIDE_CNTRCT_CNT', 'OT_AIDE_FLTM_CNT', 'OT_AIDE_PRTM_CNT', 'OT_ASTNT_CNTRCT_CNT', 'OT_ASTNT_FLTM_CNT', 'OT_ASTNT_PRTM_CNT', 'VLNTR_OTHR_CNT', 'ACTVTY_STF_OTHR_CNTRCT_CNT', 'ACTVTY_STF_OTHR_FLTM_CNT', 'ACTVTY_STF_OTHR_PRTM_CNT', 'PHYSN_OTHR_CNTRCT_CNT', 'PHYSN_OTHR_FLTM_CNT', 'PHYSN_OTHR_PRTM_CNT', 'SCL_SRVC_OTHR_STF_CNTRCT_CNT', 'SCL_SRVC_OTHR_STF_FLTM_CNT', 'SCL_SRVC_OTHR_STF_PRTM_CNT', 'STF_OTHR_CNTRCT_CNT', 'STF_OTHR_FLTM_CNT', 'STF_OTHR_PRTM_CNT', 'PHRMCST_CNTRCT_CNT', 'PHRMCST_FLTM_CNT', 'PHRMCST_PRTM_CNT', 'PHYS_THRPST_CNTRCT_CNT', 'PHYS_THRPST_FLTM_CNT', 'PHYS_THRPST_PRTM_CNT', 'PHYSN_CNT', 'PHYSN_VLNTR_CNT', 'PHYSN_ASTNT_CNT', 'PHYSN_EXT_CNTRCT_CNT', 'PHYSN_EXT_FLTM_CNT', 'PHYSN_EXT_PRTM_CNT', 'RSDNT_PHYSN_CNT', 'PDTRST_CNTRCT_CNT', 'PDTRST_FLTM_CNT', 'PDTRST_PRTM_CNT', 'PSYCHLGST_CNT', 'PHYS_THRPST_STF_CNT', 'PHYS_THRPST_CNT', 'PHYS_THRPST_ARNGMT_CNT', 'PT_AIDE_CNTRCT_CNT', 'PT_AIDE_FLTM_CNT', 'PT_AIDE_PRTM_CNT', 'PT_ASTNT_CNTRCT_CNT', 'PT_ASTNT_FLTM_CNT', 'PT_ASTNT_PRTM_CNT', 'ACTVTY_PROFNL_CNTRCT_CNT', 'ACTVTY_PROFNL_FLTM_CNT', 'ACTVTY_PROFNL_PRTM_CNT', 'RDLGY_TCHNCN_CNT', 'REG_PHRMCST_CNT', 'INHLTN_THRPST_CNT', 'RN_CNT', 'RN_CNTRCT_CNT', 'RN_FLTM_CNT', 'RN_PRTM_CNT', 'RN_VLNTR_CNT', 'RN_DRCTR_CNTRCT_CNT', 'RN_DRCTR_FLTM_CNT', 'RN_DRCTR_PRTM_CNT', 'SCL_WORKR_CNT', 'SCL_WORKR_CNTRCT_CNT', 'SCL_WORKR_FLTM_CNT', 'SCL_WORKR_PRTM_CNT', 'SPCH_PTHLGST_ARNGMT_CNT', 'SPCH_PTHLGST_CNTRCT_CNT', 'SPCH_PTHLGST_FLTM_CNT', 'SPCH_PTHLGST_PRTM_CNT', 'SPCH_PTHLGST_CNT', 'SPCH_PTHLGST_AUDLGST_CNT', 'TCHNCL_STF_NUM', 'TCHNCN_CNT', 'THRPTC_RCRTNL_CNTRCT_CNT', 'THRPTC_RCRTNL_FLTM_CNT', 'THRPTC_RCRTNL_PRTM_CNT', 'EMPLEE_CNT', 'VLNTR_CNT', 'SBUNIT_CNT', 'SBUNIT_SW', 'SBUNIT_OPRTN_SW', 'DNTL_SRGRY_SW', 'OTLRYNGLGY_SRGRY_SW', 'ENDSCPY_SRGRY_SW', 'OB_GYN_SRGRY_SW', 'OPTHMLGY_SRGRY_SW', 'ORTHPDC_SRGRY_SW', 'OTHR_SRGRY_SW', 'PAIN_SRGRY_SW', 'PLSTC_SRGRY_SW', 'FT_SRGRY_SW', 'SB_SW', 'SB_SIZE_CD', 'TCHNLGST_2_YR_RDLGC_CNT', 'TCHNLGST_ASCT_DGR_CNT', 'TCHNLGST_BS_BA_DGR_CNT', 'DLYS_STN_CNT']

Clustering of SDOH 2020 vs 2013

How can I validate this?